# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2022-07-03 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('cityname', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(blank=True, max_length=255, null=True)),
                ('area_code', models.IntegerField(blank=True, null=True)),
                ('city_code', models.CharField(blank=True, max_length=11, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('area_index', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sys_position',
                'managed': False,
            },
        ),
    ]
